services:
  api-gateway:
    build: ./api-gateway
    image: api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
      
  appointment-service:
    build: ./appointment-service
    image: appointment-service
    ports:
      - "3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
    
  notification-service:
    build: ./notification-service
    image: notification-service
    ports:
      - "3003"