services:
  api-gateway:
    build: ./api-gateway
    image: api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"

  proxy-service:
    build: ./proxy-service
    image: proxy-service
    container_name: proxy-service
    ports:
      - "3001:3001"

  mqtt-service:
    build: ./mqtt-service
    image: mqtt-service
    ports:
      - "3002"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1