services:
  api-gateway:
    build: ./api-gateway
    image: api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"

  appointment-service:
    build:
      context: ./appointment-service
      dockerfile: "${DOCKER_ARCH}.Dockerfile"
    image: appointment-service
    ports:
      - "3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1

  account-service:
    build:
      context: ./account-service
      dockerfile: "${DOCKER_ARCH}.Dockerfile"
    image: account-service
    ports:
      - "3002"

  notification-service:
    build:
      context: ./notification-service
      dockerfile: "${DOCKER_ARCH}.Dockerfile"
    image: notification-service
    ports:
      - "3003"
